# Generated by Django 5.2.1 on 2025-06-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='choice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
