# Generated by Django 5.2.1 on 2025-06-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_myuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
