# Generated by Django 5.2.1 on 2025-06-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_rename_name_product_product_name_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='product_Name',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=15),
        ),
    ]
