# Generated by Django 5.2.1 on 2025-06-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_rename_product_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_Name',
            new_name='name',
        ),
    ]
