# Generated by Django 5.2.1 on 2025-06-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_rename_product_name_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default='unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
