# Generated by Django 5.2.1 on 2025-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_order_city_order_full_name_order_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
