# Generated by Django 5.2.1 on 2025-06-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
