# Generated by Django 5.2.1 on 2025-06-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
