# Generated by Django 5.2.1 on 2025-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='unknown', max_length=100, unique=True),
        ),
    ]
